'use client';
import {useState} from 'react';
import {positionScans,scanLabels,coverageSummary,type PositionScan} from '@/lib/position-coverage';
import type {Position} from '@/lib/workspace';
import {Picker} from './forms';

export function ScanDetail({scan}:{scan:PositionScan}){return <div className="scan-detail"><p><strong>{scanLabels[scan.status]}</strong> · 核验 {scan.checkedAt}</p><p>{scan.scope}</p><p>{scan.reason}</p>{scan.reportedTotal!==null&&<p>来源列表显示 {scan.reportedTotal} 条；本网站已收录 {scan.importedRoles} 条。混合年份、机构范围及排除项见上方说明。</p>}<p className="scan-review">独立复核：{scan.review.status==='pending'?'两轮审阅尚未全部完成':scan.review.status==='accepted'?'两轮独立审阅已完成，记录与范围核对通过':'两轮独立审阅已完成，仍有下述证据或范围缺口'}</p>{scan.independentReviews?.map((r,i)=><details className="scan-review-detail" key={i}><summary>第 {i+1} 轮独立复核 · {r.decision==='accepted'?'记录与范围核对通过':'有证据或范围限制'}</summary><p>{r.note}</p>{r.sourceUrls?.map(u=><a key={u} href={u} target="_blank" rel="noopener noreferrer">独立复核来源：{u}</a>)}</details>)}<details><summary>查证过程 · {scan.attempts.length} 次</summary>{scan.attempts.map((a,i)=><div className="scan-attempt" key={i}><strong>{a.query?'检索：'+a.query:'读取来源'}</strong>{a.url&&<a href={a.url} target="_blank" rel="noopener noreferrer">{a.url}</a>}<p>{a.outcome}</p></div>)}</details>{scan.sourceUrls.length>0&&<div className="scan-sources">{scan.sourceUrls.map((u,i)=><a key={u} href={u} target="_blank" rel="noopener noreferrer">岗位查证来源 {i+1}</a>)}</div>}</div>;}

export function PositionCoverage({positions,industry,company,onOpen}:{positions:Position[];industry:string;company:string;onOpen:(id:string)=>void}){
 const [status,setStatus]=useState('all');
 const summary=coverageSummary(positionScans);
 const counts=new Map<string,number>();for(const p of positions)counts.set(p.opportunityId,(counts.get(p.opportunityId)||0)+1);
 const filtered=positionScans.filter(s=>(industry==='全部'||s.industry===industry)&&s.company.toLocaleLowerCase().includes(company.trim().toLocaleLowerCase())&&(status==='all'||s.status===status));
 return <section className="work-panel position-coverage-panel" aria-label="岗位扫描覆盖情况"><div className="panel-heading"><div><h2>203 家公司岗位扫描</h2><p>完整列表、部分收录与无法读取分别标记。列表读全也不表示每条岗位的资格、期限和余量均已确认。</p></div><Picker label="岗位扫描状态" value={status} onChange={setStatus} options={[["all","全部扫描状态"],...Object.entries(scanLabels)]}/></div><div className="scan-summary"><div><strong>{summary.attempted} / 203</strong><span>已逐家查证</span></div><div><strong>{summary.complete}</strong><span>列表已读取完整</span></div><div><strong>{summary.partial}</strong><span>岗位仅部分读取</span></div><div><strong>{summary.unresolved}</strong><span>具体岗位仍未确认</span></div></div><p className="control-hint">下方按当前行业、公司条件显示 {filtered.length} 家。完整结论仅适用于该记录注明的批次、机构范围与核验时点。</p><div className="scan-company-list">{filtered.map(s=><article key={s.opportunityId} data-scan-id={s.opportunityId}><div className="scan-company-heading"><div><button className="company-title-button" onClick={()=>onOpen(s.opportunityId)}>{s.company}</button><span>{s.industry} · 网站已录入 {counts.get(s.opportunityId)||0} 条岗位</span></div><span className={'scan-badge '+s.status}>{scanLabels[s.status]}</span></div><details><summary>范围、缺口与核验依据</summary><ScanDetail scan={s}/></details></article>)}</div>{!filtered.length&&<div className="small-empty">此范围暂无匹配的扫描记录。</div>}</section>;
}
