'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Picker,TextField} from './forms';
import {prettyTime,fieldLabels,stages,priorities,educationLabels,overseasLabels,type Kind} from '@/lib/workspace';
import type {useWorkspace} from '@/lib/use-workspace';
import type {Cache} from '@/lib/workspace-cache';
import type {SessionAction} from '@/lib/session-types';
type Store=ReturnType<typeof useWorkspace>;
function download(filename:string,value:unknown,type='application/json'){const text=typeof value==='string'?value:JSON.stringify(value,null,2),url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function show(field:string,value:unknown):string{if(value===null||value===undefined||value==='')return '未填写';if(typeof value==='boolean')return value?'是':'否';if(Array.isArray(value))return value.join('、');const labels:Record<string,Record<string,string>>={stage:stages,priority:priorities,education:educationLabels,overseas:overseasLabels};return labels[field]?.[String(value)]||String(value);}
export function StoragePanel({open,onOpenChange,store,labelFor}:{open:boolean;onOpenChange:(v:boolean)=>void;store:Store;labelFor:(id:string)=>string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[code,setCode]=useState(''),[generated,setGenerated]=useState(''),[exportText,setExportText]=useState(''),[confirm,setConfirm]=useState<SessionAction|null>(null),[copies,setCopies]=useState<Cache[]>([]),[copy,setCopy]=useState('');
 useEffect(()=>{setExportText('');if(open){setError('');void store.localCopies().then(rows=>{setCopies(rows);setCopy(store.session?.scope||rows[0]?.scope||'');}).catch(()=>{});}else{setGenerated('');setCode('');setConfirm(null);}},[open,store.session?.scope]);
 const session=store.session,pending=store.pending.length,conflicts=store.conflicts();
 async function act(action:SessionAction){setBusy(true);setError('');setMessage('');try{const result=await store.action(action,action==='recover'?code:undefined);if(result.recoveryCode)setGenerated(result.recoveryCode);if(action==='recover'){setCode('');setMessage('已找回空间；本机未同步记录会在同一空间继续同步。');}else if(action==='link_account')setMessage('当前空间已关联到 ChatGPT 账号。');else if(action==='new_guest')setMessage('已创建新的游客空间，原空间本地副本仍保留。');setConfirm(null);}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 async function resolve(kind:Kind,id:string,choice:'local'|'cloud'){setBusy(true);setError('');try{await store.resolve(kind,id,choice);}catch(e){setError(e instanceof Error?e.message:'处理失败');}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="storage-dialog"><DialogHeader><DialogTitle>保存与账号</DialogTitle><DialogDescription>默认游客云端保存，本机留一份副本。登录可选，恢复码用于找回空间。</DialogDescription></DialogHeader>
 <div className="storage-status-grid"><div><small>当前空间</small><strong>{session?.mode==='account'?'账号关联空间':session?'游客空间':'本机暂存空间'}</strong></div><div><small>云端保存</small><strong>{store.syncing?'正在同步':store.online?'已连接':'暂未连接'}</strong></div><div><small>浏览器副本</small><strong>{store.localAvailable?'已启用':'暂不可用'}</strong></div><div><small>等待同步</small><strong>{pending} 条{conflicts.length?' · 含待处理差异':''}</strong></div></div>
 <p className="storage-explanation">断网时修改先保存在当前浏览器，联网后自动尝试同步。清理网站数据会删除本机副本与访问凭证；云端记录可通过恢复码或已关联账号找回。</p>
 <div className="storage-actions"><button className="secondary-button" disabled={busy||store.syncing||store.loading} onClick={()=>void store.refresh()}>重新连接并同步</button><button className="secondary-button" disabled={!store.ready} onClick={()=>download('秋招个人记录-'+new Date().toISOString().slice(0,10)+'.json',store.backup())}>下载当前备份</button><button className="secondary-button" disabled={!store.ready} onClick={()=>setExportText(JSON.stringify(store.backup(),null,2))}>查看备份 JSON</button></div>
 {exportText&&<div className="backup-preview"><p>这是点击时的完整备份快照。如果下载未完成，可复制以下内容，保存为 .json 文件后导入。</p><textarea aria-label="当前空间 JSON 备份" value={exportText} readOnly onFocus={e=>e.target.select()}/><button className="secondary-button" onClick={()=>setExportText('')}>收起备份内容</button></div>}
 <section className="storage-section"><h3>恢复码</h3><p>{session?.hasRecovery?'已设置恢复码。只有生成时会显示完整内容，请自行保存。':'生成恢复码后，即可在其他设备找回这个空间，无需注册账号。'}</p>
 <button className="primary-button" disabled={busy||!session||pending>0} onClick={()=>session?.hasRecovery?setConfirm('recovery'):void act('recovery')}>{session?.hasRecovery?'更换恢复码':'生成恢复码'}</button>
 {generated&&<div className="recovery-result"><strong>请保存本次恢复码</strong><input aria-label="已生成恢复码" value={generated} readOnly onFocus={e=>e.target.select()}/><p>恢复码可以访问这份数据，请勿公开分享。关闭此窗口后不再显示。</p><button className="secondary-button" onClick={()=>download('秋招空间恢复码.txt','27届秋招筛选站恢复码\n'+generated+'\n请妥善保管，不要公开分享。','text/plain')}>下载恢复码</button></div>}
 <form className="recover-form" onSubmit={e=>{e.preventDefault();void act('recover');}}><TextField label="输入恢复码找回空间" value={code} onChange={setCode} placeholder="A27-…"/><button className="secondary-button" disabled={busy||!code.trim()||store.syncing}>找回空间</button></form><p className="control-hint">恢复码不会出现在链接中。找回其他空间时，当前空间的本地副本会保留。</p></section>
 <section className="storage-section"><h3>{session?.loginProvider==='none'?'游客与恢复码':'可选 ChatGPT 登录'}</h3>{session?.loginProvider==='none'?<p>此部署未配置账号登录。游客云端保存、恢复码和备份均可正常使用。</p>:session?.account?<><p>{session.account.email} · {session.account.connected?'已关联当前空间':'已登录，当前空间尚未关联'}</p><div className="storage-actions">{!session.account.connected&&<button className="secondary-button" disabled={busy||pending>0} onClick={()=>void act('link_account')}>关联当前空间到账号</button>}{!session.account.connected&&session.account.hasWorkspace&&<button className="secondary-button" disabled={busy||pending>0} onClick={()=>setConfirm('open_account')}>打开账号已有空间</button>}{session.signOutPath&&<a className="secondary-button" href={session.signOutPath} target="_top">退出 ChatGPT</a>}</div><p className="control-hint">退出 ChatGPT 后，此浏览器仍保留游客访问凭证和本地副本。共用设备请留意这些记录。</p></>:<><p>关联账号后，同一账号在其他设备登录也可以找回空间。也可以一直使用游客模式。</p>{session?.signInPath&&<a className="secondary-button" href={session.signInPath} target="_top">使用 ChatGPT 登录</a>}</>}</section>
 <section className="storage-section"><h3>本机备份与导入</h3><p>导入投递、待办、岗位与复核记录；原历史留在备份文件中。已存在且内容不同的记录需要选择保留哪份。</p><label className="backup-import">选择 JSON 备份文件<input type="file" aria-label="导入个人记录备份" accept=".json,application/json" disabled={busy||pending>0} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{if(file.size>8*1024*1024)throw new Error('备份文件超过8MB，请分批导入');const count=await store.importBackup(JSON.parse(await file.text()));setMessage('已读取 '+count+' 条备份记录，新增内容开始同步，差异内容请在下方处理。');}catch(err){setError(err instanceof Error?err.message:'导入失败');}finally{setBusy(false);}}}/></label>
 {copies.length>1&&<div className="local-copy-export"><Picker label="本机保留的空间副本" value={copy} onChange={setCopy} options={copies.map(c=>[c.scope,(c.scope===session?.scope?'当前空间':'其他空间')+' · '+prettyTime(c.updatedAt)])}/><button className="secondary-button" onClick={()=>{const c=copies.find(c=>c.scope===copy);if(c)download('秋招本机空间备份.json',store.backup(c));}}>下载所选副本</button></div>}
 </section>
 {conflicts.length>0&&<section className="storage-section"><h3>处理同步差异</h3><p>本机与云端两份内容都保留在这里。选择后再同步；如果云端又发生变化，会再次提示。</p>{conflicts.map(({op,cloud})=>{const local=op.data as Record<string,unknown>,remote=(cloud?.data||{}) as Record<string,unknown>,fields=Object.keys(local).filter(k=>!['id','opportunityId','acknowledged'].includes(k)&&JSON.stringify(local[k])!==JSON.stringify(remote[k]));return <article className="sync-conflict" key={op.mutationId}><strong>{labelFor(op.id)}</strong><p>{op.error}</p><details><summary>查看本机与云端内容</summary><dl>{fields.map(field=><div key={field}><dt>{fieldLabels[field]||field}</dt><dd><span>本机：{show(field,local[field])}</span><span>云端：{show(field,remote[field])}</span></dd></div>)}</dl></details><div className="storage-actions"><button className="secondary-button" disabled={busy||store.syncing} onClick={()=>void resolve(op.kind,op.id,'cloud')}>保留云端内容</button><button className="primary-button" disabled={busy||store.syncing} onClick={()=>void resolve(op.kind,op.id,'local')}>使用本机内容</button></div>{op.status==='blocked'&&<small>云端校验未通过时，先保留云端内容，再按提示重新填写。可先下载备份保留当前输入。</small>}</article>;})}</section>}
 <section className="storage-section"><button className="secondary-button" disabled={busy||!session||pending>0} onClick={()=>setConfirm('new_guest')}>新建游客空间</button><p className="control-hint">每个空间分别保存。切换前请保存原空间恢复码或下载备份。</p></section>
 {confirm&&<div className="storage-confirm" role="alert"><strong>{confirm==='recovery'?'确认更换恢复码？':confirm==='open_account'?'打开账号已有空间？':'创建新的游客空间？'}</strong><p>{confirm==='recovery'?'旧恢复码和其他设备的游客凭证会失效，此设备保留访问权限。请立即保存新恢复码。':confirm==='open_account'?'当前空间不会覆盖账号空间。当前本地副本仍保留，之后可通过备份导入合并。':'当前云端记录不会删除。本机将切换到新空间，原空间可用原恢复码或备份找回。'}</p><div className="storage-actions"><button className="secondary-button" disabled={busy} onClick={()=>setConfirm(null)}>取消</button><button className="primary-button" disabled={busy} onClick={()=>void act(confirm)}>确认{confirm==='recovery'?'更换':confirm==='open_account'?'打开':'创建'}</button></div></div>}
 {pending>0&&<p className="control-hint">有未同步记录时，先完成同步或处理差异，再生成恢复码、关联账号或新建空间。</p>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="saved-message" role="status">{message}</p>}</DialogContent></Dialog>;
}
