import {emptyWorkspace,type Workspace,type Saved,type Kind,type Personal,type Task,type Position,type Review} from './workspace';
import type {SessionInfo} from './session-types';
import {validatePersonal,validateTask,validatePosition,validateReview,validateEnvelope} from './workspace-validation';

export type Mutation={kind:Kind;id:string;revision:number;data:unknown;mutationId:string;origin:'local'|'backup'};
export type Pending=Mutation&{createdAt:string;status:'queued'|'conflict'|'blocked';error?:string};
export type Cache={version:1;scope:string;session:SessionInfo|null;cloud:Workspace;pending:Pending[];settled:string[];updatedAt:string};
export const newId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');
export function freshCache(scope:string,session:SessionInfo|null=null):Cache{return {version:1,scope,session,cloud:structuredClone(emptyWorkspace),pending:[],settled:[],updatedAt:new Date().toISOString()};}
export function savedFor(w:Workspace,kind:Kind,id:string):Saved<unknown>|null{return kind==='personal'?w.personal[id]||null:kind==='review'?w.reviews[id]||null:(kind==='task'?w.tasks:w.positions).find(s=>s.id===id)||null;}
export function withSaved(w:Workspace,kind:Kind,saved:Saved<unknown>):Workspace{const result={...w};if(kind==='personal')result.personal={...w.personal,[saved.id]:saved as Saved<Personal>};else if(kind==='review')result.reviews={...w.reviews,[saved.id]:saved as Saved<Review>};else if(kind==='task')result.tasks=[...w.tasks.filter(s=>s.id!==saved.id),saved as Saved<Task>];else result.positions=[...w.positions.filter(s=>s.id!==saved.id),saved as Saved<Position>];return result;}
export function project(cache:Cache):Workspace{let data=cache.cloud;for(const op of cache.pending){data=withSaved(data,op.kind,{id:op.id,data:op.data,revision:op.revision+1,updatedAt:op.createdAt});data={...data,events:[{id:'local:'+op.mutationId,kind:op.kind,itemId:op.id,summary:op.status==='conflict'?'本机记录与云端不同，等待选择':op.status==='blocked'?'本机已保存，云端校验未通过':'本机已保存，等待云端同步',changes:[],sourceUrl:null,createdAt:op.createdAt},...data.events]};}return data;}
export function sameData(a:unknown,b:unknown):boolean{const normalized=(value:unknown):unknown=>value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).filter(([k])=>k!=='acknowledged').sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,normalized(v)])):Array.isArray(value)?value.map(normalized):value;return JSON.stringify(normalized(a))===JSON.stringify(normalized(b));}
export function validated(kind:Kind,id:string,input:unknown,origin:'local'|'backup'){validateEnvelope({kind,id,revision:0,data:input});const data=kind==='personal'?validatePersonal(input):kind==='task'?validateTask(input,id):kind==='position'?validatePosition(input,id,origin==='backup'):validateReview(input,origin==='backup');return {...data,...(kind==='review'||kind==='position'?{acknowledged:(input as {acknowledged?:boolean}).acknowledged===true}: {})};}
export function mergeCloud(a:Workspace,b:Workspace){let result=a;for(const kind of ['position','review','personal','task'] as Kind[]){const rows=kind==='personal'?Object.values(b.personal):kind==='review'?Object.values(b.reviews):kind==='task'?b.tasks:b.positions;for(const row of rows)if((savedFor(result,kind,row.id)?.revision||0)<=row.revision)result=withSaved(result,kind,row);}
 const events=new Map([...a.events,...b.events].map(e=>[e.id,e]));return {...result,events:[...events.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id)).slice(0,3000),historyCursor:b.historyCursor};
}
export function mergeCaches(a:Cache|null,b:Cache):Cache{if(!a||a.scope!==b.scope)return b;const settled=[...new Set([...a.settled,...b.settled])].slice(-10000),done=new Set(settled),ops=new Map(a.pending.map(op=>[op.mutationId,op]));for(const op of b.pending){const old=ops.get(op.mutationId);ops.set(op.mutationId,old&&old.status!=='queued'&&op.status==='queued'?old:op);}return {...b,cloud:mergeCloud(a.cloud,b.cloud),settled,pending:[...ops.values()].filter(op=>!done.has(op.mutationId)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))};}
export function parseBackup(value:unknown){if(!value||typeof value!=='object')throw new Error('备份文件格式无效');const o=value as {format?:string;version?:number;workspace?:Workspace};if(o.format!=='autumn27-workspace'||o.version!==1||!o.workspace)throw new Error('请选择本站导出的备份文件');const w=o.workspace;
 if(!w.personal||!w.reviews||!Array.isArray(w.positions)||!Array.isArray(w.tasks))throw new Error('备份记录结构无效');
 const rows:[Kind,Saved<unknown>][]=[...w.positions.map(s=>['position',s] as [Kind,Saved<unknown>]),...Object.values(w.reviews).map(s=>['review',s] as [Kind,Saved<unknown>]),...Object.values(w.personal).map(s=>['personal',s] as [Kind,Saved<unknown>]),...w.tasks.map(s=>['task',s] as [Kind,Saved<unknown>])];if(rows.length>1500)throw new Error('备份记录过多，请分批导入');
 const ids=new Set<string>();return rows.map(([kind,row])=>{if(!row||typeof row.id!=='string'||ids.has(kind+':'+row.id))throw new Error('备份包含无效或重复记录');ids.add(kind+':'+row.id);const raw={...(row.data as object),...(kind==='review'||kind==='position'?{acknowledged:true}:{})};return {kind,id:row.id,data:validated(kind,row.id,raw,'backup')};});
}
